#!/bin/bash

# Generate a token, if one doesn't exists
#curl -i -u <your_username> -d '{"scopes": ["repo", "user"], "note": "getting-started"}' \
#    https://api.github.com/authorizations


MSG=$(git show -s --format=%B)
TITLE=$(git show -s --format=%s)
REMOTE_BRANCH=$(echo $MSG | grep 'GH-PR-BRANCH:' | sed s'/.*GH-PR-BRANCH: *\(.*\)/\1/')

# No branch, create one and update commit
if [ "$REMOTE_BRANCH" = "" ]; then
  REMOTE_BRANCH=$USER/$RANDOM
  AMENDED_MSG="$MSG

GH-PR-BRANCH: $REMOTE_BRANCH"
  git commit --amend -m "$AMENDED_MSG"

  CREATE_PR="yes"
fi

REMOTE_BASE=${REMOTE_BRANCH}-base

# Push branch and base
git push -f origin HEAD:refs/heads/$REMOTE_BRANCH
git push -f origin $(git show -s --format=%H HEAD~1):refs/heads/$REMOTE_BASE

# Create new PR Existing PR
if [ "$CREATE_PR" = "yes" ]; then
  # Crazy '//' syntax is bash ANSI-C quoting http://stackoverflow.com/a/7218905
  BODY=${MSG//$'\n'/\\n}
  curl -X POST -H 'Authorization: token 9234dd785e82b69cf52dd46ba5a0900c4cc19a65' \
      -H 'Content-Type: application/json' \
      -d "{\"title\": \"$TITLE\", 
           \"head\": \"$REMOTE_BRANCH\", 
           \"base\": \"$REMOTE_BASE\", 
           \"body\": \"$BODY\"}" \
      https://api.github.com/repos/helix-collective/post-commit-pr/pulls > /dev/null
fi
